name: Build Verification
# Trigger on pull requests and pushes 
on:
  push:
    branches:
      - main
      - poc/maven_publish
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: macOS-latest

    steps:
      # Step 1: Check out code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: List directory contents for debugging
      - name: List directory contents
        run: ls -alh

      # Step 3: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      # Step 4: Verify JDK installation (optional for debugging)
      - name: Verify JDK version
        run: java -version

      # Step 5: Build the project
      - name: Build KMM library
        run: ./gradlew build

      # Step 6: Run tests
      - name: Run tests
        run: ./gradlew test

      # # Step 7: Verify publication setup (optional)
      # - name: Verify publication setup
      #   run: ./gradlew publishToMavenLocal --no-configuration-cache
      #   env:
      #     ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
      #     ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
      #     ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}

      # Optional: Check the output of the build process
      # - name: Check Gradle output
      #   run: tail -n 20 build.gradle
